#!/usr/bin/env python3
import time
import rospy
from geometry_msgs.msg import Twist

def move_forvard(pub, msg):
    msg.linear.x = 2.0
    msg.angular.z = 0.0
    pub.publish(msg)

def rotate(pub, msg):
    msg.linear.x = 0.0
    msg.angular.z = 2
    pub.publish(msg)

if __name__ == '__main__':
    rospy.init_node('square')
    pub_robot1 = rospy.Publisher('/robot1/cmd_vel', Twist, queue_size=1)
    msg = Twist()
    r = rospy.Rate(0.1)
    time.sleep(1)
    while(not rospy.is_shutdown()):
        current_time = time.time()
        timeout = current_time + 2
        while current_time < timeout:
            move_forvard(pub_robot1, msg)
            time.sleep(0.05)
            current_time = time.time()
        time.sleep(1)
        current_time = time.time()
        timeout = current_time + 2.21
        while current_time < timeout:
            rotate(pub_robot1, msg)
            time.sleep(0.05)
            current_time = time.time()
        time.sleep(1)
